### ISSUE TITLE
Resize handles are always generated at position 0,0 instead of the topleft of qgraphicsitem

### ISSUE THREAD

**Issue by SurKM9** [cl0ne/resizer-item#1]
The generated resize handles always pop up at the top left corner(0,0) instead of the actual topLeft position of the rectangle. Anybody else have this issue?

**Comment by cl0ne** [comment]
Could you provide some screenshots and preferably snippets that allows to reproduce the problem?

**Comment by SurKM9** [comment]
> Could you provide some screenshots and preferably snippets that allows to reproduce the problem?

It was an issue on my side. I realized `setPos()` is necessary for the `QGraphicsItem` to work with resize handles to pop up at the right position.
